// Auto-generated by Supabase (mcp generate_typescript_types).
// Regenerate with: supabase gen types typescript --project-id ictlxbtbomiehbenvpfv
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          created_at: string
          entity: string | null
          entity_id: string | null
          id: number
          metadata: Json
          user_id: string | null
        }
        Insert: {
          action: string
          created_at?: string
          entity?: string | null
          entity_id?: string | null
          id?: never
          metadata?: Json
          user_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string
          entity?: string | null
          entity_id?: string | null
          id?: never
          metadata?: Json
          user_id?: string | null
        }
        Relationships: []
      }
      invoices: {
        Row: {
          amount_cents: number
          created_at: string
          currency: string
          description: string | null
          id: string
          plan_id: string | null
          status: string
          stripe_invoice_id: string | null
          user_id: string
        }
        Insert: {
          amount_cents: number
          created_at?: string
          currency?: string
          description?: string | null
          id?: string
          plan_id?: string | null
          status?: string
          stripe_invoice_id?: string | null
          user_id: string
        }
        Update: {
          amount_cents?: number
          created_at?: string
          currency?: string
          description?: string | null
          id?: string
          plan_id?: string | null
          status?: string
          stripe_invoice_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "invoices_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id"]
          },
        ]
      }
      memories: {
        Row: {
          caption: string | null
          content: string
          created_at: string
          created_by: string | null
          id: string
          memory_date: string | null
          storage_bytes: number
          tags: string[]
          type: string
          updated_at: string
          vault_id: string
        }
        Insert: {
          caption?: string | null
          content: string
          created_at?: string
          created_by?: string | null
          id?: string
          memory_date?: string | null
          storage_bytes?: number
          tags?: string[]
          type: string
          updated_at?: string
          vault_id: string
        }
        Update: {
          caption?: string | null
          content?: string
          created_at?: string
          created_by?: string | null
          id?: string
          memory_date?: string | null
          storage_bytes?: number
          tags?: string[]
          type?: string
          updated_at?: string
          vault_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "memories_vault_id_fkey"
            columns: ["vault_id"]
            isOneToOne: false
            referencedRelation: "vaults"
            referencedColumns: ["id"]
          },
        ]
      }
      plans: {
        Row: {
          allows_media: boolean
          created_at: string
          description: string | null
          id: string
          max_shares_per_vault: number | null
          max_vaults: number | null
          name: string
          price_cents: number
          sort_order: number
          storage_limit_mb: number
        }
        Insert: {
          allows_media?: boolean
          created_at?: string
          description?: string | null
          id: string
          max_shares_per_vault?: number | null
          max_vaults?: number | null
          name: string
          price_cents?: number
          sort_order?: number
          storage_limit_mb: number
        }
        Update: {
          allows_media?: boolean
          created_at?: string
          description?: string | null
          id?: string
          max_shares_per_vault?: number | null
          max_vaults?: number | null
          name?: string
          price_cents?: number
          sort_order?: number
          storage_limit_mb?: number
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string
          id: string
          name: string
          push_enabled: boolean
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email: string
          id: string
          name?: string
          push_enabled?: boolean
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string
          id?: string
          name?: string
          push_enabled?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      push_tokens: {
        Row: {
          created_at: string
          id: string
          platform: string | null
          token: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          platform?: string | null
          token: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          platform?: string | null
          token?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          auto_renew: boolean
          created_at: string
          current_period_end: string | null
          current_period_start: string
          plan_id: string
          status: string
          storage_used_bytes: number
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          auto_renew?: boolean
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string
          plan_id?: string
          status?: string
          storage_used_bytes?: number
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          auto_renew?: boolean
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string
          plan_id?: string
          status?: string
          storage_used_bytes?: number
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id"]
          },
        ]
      }
      vault_shares: {
        Row: {
          created_at: string
          id: string
          role: string
          user_id: string
          vault_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          role?: string
          user_id: string
          vault_id: string
        }
        Update: {
          created_at?: string
          id?: string
          role?: string
          user_id?: string
          vault_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vault_shares_vault_id_fkey"
            columns: ["vault_id"]
            isOneToOne: false
            referencedRelation: "vaults"
            referencedColumns: ["id"]
          },
        ]
      }
      vaults: {
        Row: {
          cover_image: string | null
          created_at: string
          description: string | null
          id: string
          name: string
          owner_id: string
          updated_at: string
        }
        Insert: {
          cover_image?: string | null
          created_at?: string
          description?: string | null
          id?: string
          name: string
          owner_id: string
          updated_at?: string
        }
        Update: {
          cover_image?: string | null
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          owner_id?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      can_access_vault: { Args: { v_id: string }; Returns: boolean }
      can_edit_vault: { Args: { v_id: string }; Returns: boolean }
      is_vault_owner: { Args: { v_id: string }; Returns: boolean }
      shares_vault_with: { Args: { target: string }; Returns: boolean }
      share_vault_by_email: {
        Args: { p_vault_id: string; p_email: string; p_role?: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database["public"]

export type Tables<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T]["Update"]
